# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abv', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('ba_score', models.SmallIntegerField()),
                ('isi_score', models.SmallIntegerField()),
                ('link', models.CharField(default='Link to Beer', max_length=100)),
                ('name', models.CharField(default='Name', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Brewer', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chilled', models.BooleanField(default=False)),
                ('filled', models.BooleanField(default=False)),
                ('stocked', models.BooleanField(default=False)),
                ('tapped', models.BooleanField(default=False)),
                ('chilled_date', models.DateField(default=django.utils.timezone.now)),
                ('emptied_date', models.DateField(default=django.utils.timezone.now)),
                ('stocked_date', models.DateField(default=django.utils.timezone.now)),
                ('tapped_date', models.DateField(default=django.utils.timezone.now)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Beer')),
            ],
        ),
        migrations.CreateModel(
            name='Kegerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_date', models.DateField(default=django.utils.timezone.now)),
                ('clean_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='Name', max_length=50, unique=True)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Floor')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Style', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='keg',
            name='kegerator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Kegerator'),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Brewer'),
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Style'),
        ),
    ]
