# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
