# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Beer')),
            ],
        ),
    ]
