# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='number',
            new_name='rating',
        ),
    ]
